# Generated by Django 3.1.6 on 2021-02-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210215_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
